---
development:
  cloud_name: dlwyepfe6
  api_key: '511413483619817'
  api_secret: opTDXHqi_y7e-PMNSKrWf9i2KPk
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dlwyepfe6
  api_key: '511413483619817'
  api_secret: opTDXHqi_y7e-PMNSKrWf9i2KPk
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dlwyepfe6
  api_key: '511413483619817'
  api_secret: opTDXHqi_y7e-PMNSKrWf9i2KPk
  enhance_image_tag: true
  static_file_support: false
